version: "3.1"
services:
    app:
        build: .
        environment:
            MINTGUARD_DATABASE_URL: "include my database url here"
            PORT: 3000
        ports:
            - 3000:3000
            - 5432:5432
